### ISSUE TITLE
Not working with floating windows

### ISSUE THREAD

**Issue by ambadyanands** [xiyaowong/link-visitor.nvim#2]
Hi, I tried this plugin's commands from the floating windows created by the [`:PackerStatus`](https://github.com/wbthomason/packer.nvim) and [`:Mason`](https://github.com/williamboman/mason.nvim) commands and the links are not getting opened. But it works if I try opening links from regular windows. Please let me know if I should provide any additional information.

Thanks.

**Comment by xiyaowong** [comment]
Does the latest commit fix your issue? @ambadyanands

**Comment by ambadyanands** [comment]
@xiyaowong Yes, the issue is fixed, thanks :heart:
