### ISSUE TITLE
Feature request: Expand the scope of VisitLinkNearCursor to entire buffer

### ISSUE THREAD

**Issue by ambadyanands** [xiyaowong/link-visitor.nvim#3]
Currently the `VisitLinkNearCursor` only searches in the current line. It would be great if it can search in the entire buffer (or at least in the visible region of the buffer) until it finds a link nearby.

I know `VisitLinkInBuffer` already shows all links in the current buffer, but it still needs the user to choose a link from the list while the proposed suggestion is to automate the process by choosing the nearest link by default. This may require two commands to find link forwards and backwards relative to the cursor position.

Thanks.

**Comment by xiyaowong** [comment]
nice idea

**Comment by xiyaowong** [comment]
Sorry for the delayed response to this issue. @ambadyanands
